source "https://rubygems.org"

gem 'rake', '~> 12.3.3'
gem "puppet", ENV['PUPPET_GEM_VERSION'] || '~> 3.8.0'
gem "puppet-lint"
gem "rspec-puppet", '~> 2.3.2'
gem "puppetlabs_spec_helper"
gem "rspec-system-puppet"
gem "vagrant-wrapper"
gem "puppet-syntax"

group :development do
  gem "puppet-blacksmith"
end
