# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    twig:
        mode: lazy
    # your filter sets are defined here
    filter_sets:
        # use the default cache configuration
        cache: ~
        program_thumb:
            filters:
                relative_resize:
                    heighten: 58
            post_processors:
                jpegoptim: { strip_all: true, quality: 85, progressive: true }
                # optipng: { strip_all: true, level: 6 }
        page_thumb:
            filters:
                relative_resize:
                    widen: 64
            post_processors:
                jpegoptim: { strip_all: true, quality: 95, progressive: true }
                # optipng: { strip_all: true, level: 5 }
        notification_thumb:
            filters:
                downscale:
                    max: [1024, 512]
            post_processors:
                jpegoptim: { strip_all: true, quality : 95, progressive: false }
                # optipng: { strip_all: true, level: 5 }
