twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        analytics: "%env(analytics)%"
        timezone: "%timezone%"
        streams_proxy: "%env(streams_proxy)%"
        api_url: "%env(API_URL)%"
        legacy: "%env(LEGACY)%"
        adsense_key: "%env(ADSENSE_KEY)%"
        adsense_tag_radio_horiz_key: "%env(ADSENSE_TAG_RADIO_HORIZ_KEY)%"
        adsense_tag_radio_vert_key: "%env(ADSENSE_TAG_RADIO_VERT_KEY)%"
        adsense_tag_radio_horiz_fix_key: "%env(ADSENSE_TAG_RADIO_HORIZ_FIX_KEY)%"
        geocode: "%env(GEOCODE)%"

when@test:
    twig:
        strict_variables: true
