twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        analytics: "%env(analytics)%"
        timezone: "%timezone%"
        streams_proxy: "%env(streams_proxy)%"
        api_url: "%env(API_URL)%"
        legacy: "%env(LEGACY)%"
        adsense_key: "%env(ADSENSE_KEY)%"

when@test:
    twig:
        strict_variables: true
