twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        analytics: "%env(analytics)%"
        timezone: "%timezone%"
        streams_proxy: "%env(streams_proxy)%"
        streams_proxy_key: "%env(STREAMS_PROXY_KEY)%"
        api_url: "%env(API_URL)%"
#        legacy: "%env(LEGACY)%"
        adsense_key: "%env(ADSENSE_KEY)%"
        adsense_tag_radio_horiz_key: "%env(ADSENSE_TAG_RADIO_HORIZ_KEY)%"
        adsense_tag_radio_vert_key: "%env(ADSENSE_TAG_RADIO_VERT_KEY)%"
        adsense_tag_radio_vert2_key: "%env(ADSENSE_TAG_RADIO_VERT2_KEY)%"
        adsense_tag_radio_horiz_fix_key: "%env(ADSENSE_TAG_RADIO_HORIZ_FIX_KEY)%"
        geocode: "%env(GEOCODE)%"
#        amazon_affiliate_id: "%env(AMAZON_AFFILIATE_ID)%"
    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true
