fixtures:
  symlinks:
    inifile: "#{source_dir}"
    create_ini_settings_test: "#{source_dir}/spec/fixtures/create_ini_settings_test"
    create_multiple_ini_settings: "#{source_dir}/spec/fixtures/create_multiple_ini_settings"
    inherit_ini_setting: "#{source_dir}/spec/fixtures/inherit_ini_setting"
    inherit_test1: "#{source_dir}/spec/fixtures/inherit_test1"
