fixtures:
  symlinks:
    nodejs: "#{source_dir}"
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.12.0"
    gcc:
      repo: "git://github.com/puppetlabs/puppetlabs-gcc.git"
      ref: "0.3.0"
