source 'https://rubygems.org'

gem 'capistrano'
gem 'capistrano-symfony', :github => 'capistrano/symfony', :branch => 'master'
gem 'capistrano-npm'
gem 'capistrano-upstart-service'
gem 'capistrano-yarn'
