doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: pool
            pool: cache.system
        query_cache_driver:
            type: pool
            pool: cache.system
        result_cache_driver:
            type: pool
            pool: cache.app

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
