liip_imagine:
    loaders:
        default:
            filesystem:
                data_root:
                    - '%kernel.project_dir%/../var/shared/'
                    - '%kernel.project_dir%/public/'
