---
appveyor.yml:
  delete: true
# override default cells to replace centos-7 with debian-8
.travis.yml:
  docker_sets:
  - set: docker/ubuntu-14.04
  - set: docker/debian-8
  extras:
  - rvm: 2.1.9
    script: bundle exec rake rubocop

NOTICE:
  unmanaged: true

spec/spec_helper.rb:
  allow_deprecations: true
