#syntax=docker/dockerfile:1.4

FROM node:lts-alpine

RUN apk update && \
    apk upgrade && \
    apk add git && \
    apk add bash

RUN mkdir -p /app/spa
COPY ./spa/ /app/spa/

WORKDIR /app/spa

#RUN npm i caniuse-lite browserslist
#RUN npx update-browserslist-db@latest

RUN apk update && \
    apk upgrade && \
    apk add git

RUN npm install

#CMD [ "npm", "run", "dev"]