FROM node:16-bookworm

RUN apt-get update \
    && apt-get -y install \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /usr/app

# Copy package.json and package-lock.json
COPY ./package*.json ./

# Copy application code
COPY ./ .

# Install dependencies
RUN yarn install

# CMD ["npm", "start"]

ENTRYPOINT ["tail", "-f", "/dev/null"]
