FROM node:24-alpine

RUN apk add --no-cache \
  chromium nss freetype harfbuzz \
  ca-certificates ttf-freefont \
  bash git

# Set working directory
WORKDIR /usr/app

# Copy package.json and package-lock.json
COPY ./package*.json ./

# Copy application code
COPY ./ .

# Install dependencies
RUN npm install

# CMD ["npm", "start"]

ENTRYPOINT ["tail", "-f", "/dev/null"]
