Gemfile:
  puppet_version: '>= 3.0'
Rakefile:
  strict_variables: false
spec/spec_helper_acceptance.rb:
  modules:
    - name: stahnma-epel
      version: 0.1.0
      osfamily: RedHat
    - name: puppetlabs-apache
      version: 1.1.0
.travis.yml:
  forge_password: "P0disPGZg4I9kuO98yZOPxpdJjBWV+3U9iFCfRKpCO4jzBiqkCaofnr79Iy+7aqyWAKdbp54JUIbKenvz+WixbVjxvJNiTV991B6anaDXOZfk5oudoxy+hMmkor881ZznWJgwaim4BA3qcTghpIhMSqFP5FF0CaJUfzTEaj73s8="
