---
# This file is managed centrally by modulesync
#   https://github.com/maestrodev/puppet-modulesync

sudo: false

before_install:
  - rm -f Gemfile.lock

rvm:
  - "2.0"

env:
  - PUPPET_VERSION="~> 4.0.0"
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.5.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.2.0"

matrix:
  exclude:
    # No support for Ruby 2.0 before Puppet 3.2
    - rvm: '2.0'
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: '2.0'
      env: PUPPET_VERSION="~> 3.0.0"
    - rvm: '2.0'
      env: PUPPET_VERSION="~> 3.1.0"
    # Puppet < 3.5.0 is broken under ruby 2.1 https://tickets.puppetlabs.com/browse/PUP-1243
    - rvm: '2.1'
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: '2.1'
      env: PUPPET_VERSION="~> 3.0.0"
    - rvm: '2.1'
      env: PUPPET_VERSION="~> 3.1.0"
    - rvm: '2.1'
      env: PUPPET_VERSION="~> 3.2.0"
    - rvm: '2.1'
      env: PUPPET_VERSION="~> 3.3.0"
    - rvm: '2.1'
      env: PUPPET_VERSION="~> 3.4.0"

deploy:
  provider: puppetforge
  user: maestrodev
  password:
    secure: "P0disPGZg4I9kuO98yZOPxpdJjBWV+3U9iFCfRKpCO4jzBiqkCaofnr79Iy+7aqyWAKdbp54JUIbKenvz+WixbVjxvJNiTV991B6anaDXOZfk5oudoxy+hMmkor881ZznWJgwaim4BA3qcTghpIhMSqFP5FF0CaJUfzTEaj73s8="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    condition: "$PUPPET_VERSION = '~> 3.6.0'"
